# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.20.1'
  displayName: 'Install Node.js'
- script: |
    npm install
  displayName: 'npm install'
- script:
    npx browserslist@latest --update-db
#   displayName: 'Installing angular globally'
# - script:
#     ng --version
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQube-HRSuiteUI'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '00398d794fd32769cf347e170582733fecb7e696'
    cliProjectName: 'HRSuiteUI'
    cliSources: './src'
    extraProperties: |
      sonar.javascript.file.suffixes=.js,.jsx
      sonar.typescript.file.suffixes=.ts,.tsx
      sonar.sourceEncoding=UTF-8
- script: |
      FILTERED_PARAMS=$(echo $SONARQUBE_SCANNER_PARAMS | sed 's/"sonar.branch.name":"[^"]*"\,//g')
      echo "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$FILTERED_PARAMS"
  displayName: Filter out non-CE sonar parameters
- task: SonarQubeAnalyze@5
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
- script:
    npm run build-prod
  displayName: 'Building angular project'
- task: PublishBuildArtifacts@1
  displayName: 'Publish to artifacts'
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'HRSuite'
    publishLocation: 'Container'