

export class EndPointModel {
    BASE_URL: string;
    BASE_GETTOKEN_ENDPOINT: string;
    BASE_GETDOCUMENT_ENDPOINT: string;
    BASE_UILOADBASEVALUES_ENDPOINT: string;
    BASE_FETCHALLMANDATES_ENDPOINT: string;
    BASE_GETLOCATION_ENDPOINT: string;
    BASE_FETCHMANDATESBYID_ENDPOINT: string;
    BASE_UPDATEMANDATES_ENDPOINT: string;
    BASE_UPDATEMANDATESTRANSACTIONDETAILS_ENDPOINT: string;
    BASE_GETCHECKUSER_ENDPOINT: string;
    BASE_UPDATE_Assignment: string;
    BASE_UPLOADDOCUMENT_ENDPOINT: string;
    BASE_VIEWMANDATES_ENDPOINT: string;
    BASE_UPDATEASSIGNMANDATES_ENDPOINT: string;
    BASE_DELETESCHEDULE_ENDPOINT: string;
    BASE_UPDATEDELEGATEMANDATES_ENDPOINT: string;
    BASE_DELETEASSIGNMENT_ENDPOINT: string;
    BASE_UPDATE_SCHEDULES: string;
    BASE_FETCHMANDATESBYREQUIREMENTID_ENDPOINT: string;
    BASE_SEARCHCANDIDATES_ENDPOINT: string;
	 BASE_FETCHALLCANDIDATES_ENDPOINT:string;
    BASE_FETCHCANDIDATEUILOAD_ENDPOINT:string;
    BASE_FETCHCANDIDATEBYID_ENDPOINT:string;
    BASE_INSERTCANDIDATE_ENDPOINT:string;
    BASE_UPDATECANDIDATE_ENDPOINT:string;
    BASE_UPLOADPERSONDOCUMENT_ENDPOINT: string;
    BASE_FETCHDATATOUILOAD_ENDPOINT:string;
}
