export class CandidateDummyModel {


// NewCandidateDetails: {
//     FirstName: "",
//     LastName:"" ,
//     PhotoStorage: "",
//     DateOfBirth: "",
//     Gender: 0,
//     Nationality: 0,
//     CountryOfOrigin: 0,
//     MaritalStatus: 0,
//     BloodGroup: 0,
//     IsDifferentlyabled: false,
//     DisabilityPercentage: 0.0,
//     Status: 0,
//     Qualifications: "",
//     WorkExperiences: "",
//     LstSkillDetails: "",
//     WorkPermits: [],
//     LstCandidateOfferDetails: [
//         {
//             CandidateId: 3460,
//             JobTitle: "",
//             IndustryId: 0,
//             WorkPremise: 0,
//             Location: 9,
//             State: 0,
//             Country: 0,
//             SkillCategory: 0,
//             Zone: 0,
//             TenureType: 0,
//             TenureInterval: 0.0,
//             CompanyId: 0,
//             ClientId: 62,
//             ClientContractId: 24,
//             ClientContactId: 9,
//             Designation: "",
//             DateOfJoining: new Date,
//             EndDate: new Date,
//             IsAutoupdateEndDate: false,
//             EffectivePayPeriodId: 0,
//             NoticePeriodDays: 0,
//             SourceType: 0,
//             IsClientApprovedBasedOn: 0,
//             JobType: 0,
//             EmploymentType: 0,
//             FUNCTIONALAREA: 0,
//             IsAadhaarExemptedState: false,
//             Aadhaar: "",
//             PANAckowlegementNumber: 0,
//             IsPANExists: false,
//             IsPanApplied: false,
//             LetterTemplateId: 0,
//             RequestedBy: 3,
//             RequestType: 0,
//             MandateRequirementId: 0,
//             OnBoardingType: 0,
//             ProxyRemarks: "",
//             SalaryRemarks: "",
//             IsSelfRequest: false,
//             TeamProxyRequest: "",
//             ModuleTransactionId: 0,
//             Modetype: 0,
//             OnCostInsurance: 0.0,
//             FixedInsuranceDeduction: 0.0,
//             LstCandidateRateSet: "",
//             MyProperty: 0,
//             Id: 0,
//             CreatedOn: null,
//             LastUpdatedOn: null,
//             CreatedBy: "",
//             LastUpdatedBy: ""
//         }
//     ],
//     LstCandidateLetterTransaction: "",
//     CandidateCommunicationDtls: {
//         Id: 0,
//         CandidateId: 0,
//         AddressDetails: "",
//         ContactDetails: "",
//         LstAddressdetails: "",
//         LstContactDetails: [
//             {
//                 CommunicationCategoryTypeId: 0,
//                 PrimaryMobile: 0,
//                 PrimaryMobileCountryCode: 0,
//                 AlternateMobile: "",
//                 AlternateMobileCountryCode: "",
//                 PrimaryEmail: "",
//                 AlternateEmail: "",
//                 EmergencyContactNo: "",
//                 LandlineStd: "",
//                 LandLine: "",
//                 LandLineExtension: "",
//                 PrimaryFax: "",
//                 AlternateFax: "",
//                 IsDefault: false
//             }
//         ],
//         Modetype: 0
//     },
//     LstCandidateFamilyDetails: "",
//     LstCandidateDocuments: "",
//     LstCandidateProfileDetails: "",
//     LstCandidateBankDetails: "",
//     CandidateCareerDtls: "",
//     CandidateOtherData: {
//         Id: 0,
//         CandidateId: 0,
//         StatutoryDetailData: "",
//         LstCandidateStatutoryDtls: [
//             {
//                 Id: 0,
//                 CandidateId: 0,
//                 IsPreviouslyEmployed: false,
//                 PFNumber: 324234,
//                 UAN: 23423,
//                 ESICNumber: 23423423,
//                 PAN: 23423423,
//                 storageDetails: "",
//                 DocumentId: 0,
//                 Modetype: 0
//             }
//         ],
//         MiscellaneousData: "",
//         Modetype: 0
//     },
//     CandidateMandateMapping: "",
//     Modetype: 0,
//     Id: 4,
//     CreatedOn: 0000-00-00T00:00:00,
//     LastUpdatedOn: 0000-00-00T00:00:00,
//     CreatedBy: "",
//     LastUpdatedBy: ""
// },
// OldCandidateDetails: {
//     FirstName: Arul Mano,
//     LastName: ,
//     PhotoStorage: "",
//     DateOfBirth: 2009-00-07T00:00:00,
//     Gender: 0,
//     Nationality: 0,
//     CountryOfOrigin: 0,
//     MaritalStatus: 0,
//     BloodGroup: 0,
//     IsDifferentlyabled: false,
//     DisabilityPercentage: 0.0,
//     Status: 0,
//     Qualifications: "",
//     WorkExperiences: "",
//     LstSkillDetails: "",
//     WorkPermits: [],
//     LstCandidateOfferDetails: [
//         {
//             CandidateId: 3460,
//             JobTitle: "",
//             IndustryId: 0,
//             WorkPremise: 0,
//             Location: 9,
//             State: 0,
//             Country: 0,
//             SkillCategory: 0,
//             Zone: 0,
//             TenureType: 0,
//             TenureInterval: 0.0,
//             CompanyId: 0,
//             ClientId: 62,
//             ClientContractId: 24,
//             ClientContactId: 9,
//             Designation: Designer,
//             DateOfJoining: 2009-00-05T00:00:00,
//             EndDate: 0000-00-00T00:00:00,
//             IsAutoupdateEndDate: false,
//             EffectivePayPeriodId: 0,
//             NoticePeriodDays: 0,
//             SourceType: 0,
//             IsClientApprovedBasedOn: 0,
//             JobType: 0,
//             EmploymentType: 0,
//             FUNCTIONALAREA: 0,
//             IsAadhaarExemptedState: false,
//             Aadhaar: "",
//             PANAckowlegementNumber: ,
//             IsPANExists: false,
//             IsPanApplied: false,
//             LetterTemplateId: 0,
//             RequestedBy: 3,
//             RequestType: 0,
//             MandateRequirementId: 0,
//             OnBoardingType: 0,
//             ProxyRemarks: ,
//             SalaryRemarks: "",
//             IsSelfRequest: false,
//             TeamProxyRequest: "",
//             ModuleTransactionId: 0,
//             Modetype: 0,
//             OnCostInsurance: 0.0,
//             FixedInsuranceDeduction: 0.0,
//             LstCandidateRateSet: "",
//             MyProperty: 0,
//             Id: 0,
//             CreatedOn: 0000-00-00T00:00:00,
//             LastUpdatedOn: 0000-00-00T00:00:00,
//             CreatedBy: "",
//             LastUpdatedBy: ""
//         }
//     ],
//     LstCandidateLetterTransaction: "",
//     CandidateCommunicationDtls: {
//         Id: 0,
//         CandidateId: 0,
//         AddressDetails: "",
//         ContactDetails: "",
//         LstAddressdetails: "",
//         LstContactDetails: [
//             {
//                 CommunicationCategoryTypeId: 0,
//                 PrimaryMobile: 9206388992,
//                 PrimaryMobileCountryCode: 90,
//                 AlternateMobile: "",
//                 AlternateMobileCountryCode: "",
//                 PrimaryEmail: dpkdpk.kesh@gmail.com,
//                 AlternateEmail: "",
//                 EmergencyContactNo: "",
//                 LandlineStd: "",
//                 LandLine: "",
//                 LandLineExtension: "",
//                 PrimaryFax: "",
//                 AlternateFax: "",
//                 IsDefault: false
//             }
//         ],
//         Modetype: 0
//     },
//     LstCandidateFamilyDetails: "",
//     LstCandidateDocuments: "",
//     LstCandidateProfileDetails: "",
//     LstCandidateBankDetails: "",
//     CandidateCareerDtls: "",
//     CandidateOtherData: {
//         Id: 0,
//         CandidateId: 0,
//         StatutoryDetailData: "",
//         LstCandidateStatutoryDtls: [
//             {
//                 Id: 0,
//                 CandidateId: 0,
//                 IsPreviouslyEmployed: false,
//                 PFNumber: 324234,
//                 UAN: 23423,
//                 ESICNumber: 23423423,
//                 PAN: 23423423,
//                 storageDetails: "",
//                 DocumentId: 0,
//                 Modetype: 0
//             }
//         ],
//         MiscellaneousData: "",
//         Modetype: 0
//     },
//     CandidateMandateMapping: "",
//     Modetype: 0,
//     Id: 4,
//     CreatedOn: 0000-00-00T00:00:00,
//     LastUpdatedOn: 0000-00-00T00:00:00,
//     CreatedBy: "",
//     LastUpdatedBy: ""
// },
// CandidateRateSet: "",
// customObject0: "",
// customObject2: "",
// Id: 0



// }

}