export const appSettings = {
  appTitle: 'HR Suite',
  appLogo: '/assets/images/logo/logo.jpg',
  SECURITY_ENDPOINT: "api/Security/GetAuthConfigByUrlCodeAndAuthKey?",
  SECURITY_COMPANYANDCLIENT_ENDPOINT: '/api/Security/GetAuthConfigDataByCompanyAndClient?',
  SECURITY_REQUESTOTP: '/api/Security/RequestOtpToResetPwd?',
  SECURITY_VALIDATEOTP: '/api/Security/ValidateOtpForPwdReset',
  SECURITY_UPDATEPASSWORD: '/api/Security/UpdatePassword',
  SECURITY_AUTHENTICATION: '/api/Security/AuthenticateUser',
  SECURITY_LOGOUT: 'api/Security/Logout',
  SECURITY_CHANGEPASSWORD: '/api/Security/ChangePassword',
  SECURITY_UPDATEROLEINSESSION: 'api/Security/UpdateRoleInSession',
  SECURITY_SENDTOP: 'api/OTP/SendOTPForApprovalRequest',
  SECURITY_VERIFYTOP: 'api/OTP/VerifyApprovalRequestOTP',
  SECURITY_GETMENUITEMSBYCLIENTID : 'api/Security/GetMenuByUserAndClient?',

  SECURITY_GENERATESECRETKEY: 'api/TwoFactorAuthenticator/GenerateQRCode',
  SECURITY_VERIFYCODE: 'api/TwoFactorAuthenticator/VerifyCode',
  SECURITY_SENDOTPFORMFA: 'api/Security/SendOTPForMFA',
  SECURITY_GENERATEQRCODEFORMFA: 'api/Security/GetQRCodeForMFA/',
  SECURITY_ENABLEMFA: 'api/Security/EnableMFA',
  SECURITY_DISABLEMFA: 'api/Security/DisableMFA',
  SECURITY_VERIFYMFA: 'api/Security/VerifyMFA/',
  SECURITY_GETSESSION: 'api/security/GetSession/',
  GET_SPLOGIN: 'api/auth/SPLogin',

  GETCOUNTRY: 'api/Location/GetCountries',
  POSTCOUNTRY: 'api/Location/InsertCountryDetails',
  PUTCOUNTRY: 'api/Location/UpdateCountryDetails',
  DELETECOUNTRY: 'api/Location/DeleteCountryDetails',
  GETSTATES: 'api/Location/GetStateListByCountryId?',
  PUTSTATES: 'api/Location/UpdateStateDetails',
  POSTSTATES: 'api/Location/InsertStateDetails',
  DELETESTATES: 'api/Location/DeleteStateDetails',
  GET_BRANCH_BY_BANKID: 'api/Bank/FetchBankBranchByBankId?',
  GET_ALLSCALES: 'api/Scale/GetAllScales',
  GET_STATEBYID: 'api/Location/FetchStateById?',


  GETCITIES: 'api/Location/GetCityListByStateId?',
  PUTCITIES: 'api/Location/UpdateCityDetails',
  POSTCITIES: 'api/Location/InsertCityDetails',
  DELETECITIES: 'api/Location/InActivateCityDetails',
  GETCITYBYID: 'api/Location/FetchCityById?',
  GETCOMPANYSETTINGS: 'api/Company/GetCompanySettings/',
  GETCOMPANYREQUIREDSETTINGS: "api/CompanySettings/GetRequiredCompanySettingsList?",


  GETMINIMUMWAGES: 'api/MinimumWages/GetMinimumWagesMappingList',
  EDITMINIMUMWAGES: 'api/MinimumWages/GetMinimumWagesMappingById?',
  DELETEWAGES: 'api/MinimumWages/InActivateMinimumWagesMapping',
  PUTWAGES: 'api/MinimumWages/UpsertMinimumWagesMapping',
  POSTWAGES: 'api/MinimumWages/UpsertMinimumWagesMapping',
  GETSKILLCATEGORY: 'api/MinimumWages/GetSkillCategoryList',
  GETZONES: 'api/MinimumWages/GetZoneList',
  GETINDUSTRYS: 'api/Industry/GetIndustryList',
  GETPRODUCTS: 'api/Product/GetAllProduct',

  // ** Onboarding Service start

  GET_ONBOARDING_MASTER_INFO: 'api/OnBoarding/GetOnboardingMasterInfo/',
  GET_ONBOARDING_REGENERATEAL_INFO: 'api/OnBoarding/GetOnboardingInfoForRegenerateAL',
  GET_MANDATESFOR_ONBOARDING_BYUSERID: 'api/OnBoarding/GetActiveMandatesForOnboardingByUserId/',
  GET_CANDIDATE_BYASSIGNMENTID: 'api/OnBoarding/GetCandidateDetailsByAssignmentId/',
  GET_SKILANDZONE_BYSTATEANDINDUSTRY: 'api/OnBoarding/GetSkillCategoriesAndZonesByStateAndIndustry/',
  UPSERTCANDIDATE: 'api/OnBoarding/UpsertOnBoardingCandidate',
  GET_LETTERTEMPLATE: 'api/OnBoarding/GetLetterTemplateDetails/',
  GET_DOCUMENTDETAILS: 'api/OnBoarding/GetDocumentDetailsbyCandidateId/',
  GET_ONBOARDING_LISTING: 'api/OnBoarding/GetOnboardingCandidateList/',
  GET_ONBOARDING_CANDIDATES: 'api/OnBoarding/GetOnboardingCandidates/',
  GET_ONBOARDING_ALLCANDIDATES: 'api/OnBoarding/GetAllenOnboardingCandidates?',
  GETCANDIDATE: 'api/Candidate/FetchCandidate?',
  GETCANDIDATEDATAUSINGCANDIDATEID: 'api/Candidate/FetchCandidateDataUsingCandidateId?',
  GET_CANDIDATE_QC_INFO: 'api/OnBoarding/GetCandidateQualityCheckdetails/',
  POST_CANDIDATE_QC_INFO: 'api/OnBoarding/UpdateCandidateQualityDocumentDetails',
  POST_CALCULATESALARYBREAKUP: 'api/OnBoarding/CalculateSalaryBreakUp',
  DELETE_CANDIDATEDOCUMENTS: 'api/Candidate/DeleteCandidateDocuments',
  POST_PREVIEWLETTER: 'api/onboarding/previewletter',
  GET_MIGRATIONMASTERINFO: 'api/OnBoarding/GetMigrationMasterInfo/',
  GET_CANDIDATEDOCUMENTCHECK: 'api/Candidate/DuplicateCandidateDocumentCheck?',
  GET_CANDIDATEVIEWSDETAILS: 'api/OnBoarding/ExportCandidateDetailsForThirdParty',
  UPDATE_CLAIMONBOARDINGREQUEST: 'api/OnBoarding/UpdateClaimOnBoardingRequest?',
  UPDATE_VOIDONBOARDINGREQUEST: 'api/OnBoarding/UpdateCandidateOfferDetailsVoidTransaction?',
  UPDATE_CANDIDATENOTJOINED: 'api/OnBoarding/UpdateCandidateOfferDetailAsNotJoined?',
  GET_ISVALIDTOMAKEOFFER: 'api/OnBoarding/IsValidToMakeOffer?',
  GETONBOARDINGCANDIDATEVIEW: 'api/OnBoarding/GetOnboardingCandidateDetailsView/',
  POSTEMPLOYEEMIGRATEREPORT: 'api/OnBoarding/InsertMigratedEmployee',
  BULK_CANDIDATE_UPLOAD: 'api/OnBoarding/UploadBulkCandidateDetailed?',
  GET_ONBOARDINGSUBMISSION_LISTING: 'api/OnBoarding/GetOnboardingSubmissionList/',
  POST_VALIDATECANDIDATETOCANCELOFFER: 'api/OnBoarding/ValidateCandidateToCancelOffer?',
  POST_VALIDATECANDIDATETOREGENERATEAL: 'api/OnBoarding/ValidateCandidateToRegenerateAL?',
  GET_SEPARATEDCANDIDATELIST: 'api/OnBoarding/GetSeparatedCandidateList/',
  UPDATE_ANDVALIDATETOMAKEOFFERFORSEPARATION: 'api/OnBoarding/ValidateAndUpdateToMakeOfferForSeparation?',
  UPDATE_SEPARATEDCANDIDATEOFFERASACTIVE: 'api/OnBoarding/ReUpdateSeparatedCandidateOfferAsActive?',
  POST_VALIDATECANDIDATEINFORMATION: 'api/OnBoarding/ValidateCandidateInformation',
  POST_CANDIDATEOFFERNEWDOJ: 'api/OnBoarding/UpdateCandidateOfferNewDOJ',
  GET_SBLOOKUPDETAILS: 'api/Onboarding/LoadNapsLookupDetailsbyContractId?',
  GET_ONBOARDINGADDITIONALINFO: 'api/OnBoarding/GetOnboardingAdditionalInfo/',
  FETCH_SURVEYQUESTIONS: 'api/OnBoarding/FetchSurveyQuestions?',

  REGENERATE_AL: 'api/OnBoarding/RegenerateAL',
  PREVIEWLETTER_AL: 'api/OnBoarding/PreviewLetterNew',
  GET_DYNAMICFIELDDETAILS: 'api/OnBoarding/GetDynamicFieldDetails/',
  POST_DYNAMICFIELDVALUE: 'api/OnBoarding/UpsertDynamicFieldsValue',
  GET_DYNAMICFIELDDETAILSBYCANDIDATEID: 'api/OnBoarding/GetDynamicFieldsValue/',
  GETPROCESSLOG: 'api/WorkFlow/GetProcessLog/',
  GETCANDIDATEDETAILSFORPROCESSLOGUI: 'api/OnBoarding/GetCandidateDetailsForProcessLogUI?',
  GET_DOWNLOADCANDIDATEENTIREINFORMATION: 'api/OnBoarding/DownloadCandidateEntireInformation/',
  GET_MASTERINFO: 'api/ELC/GetMasterInfo/',
  GETCANDIDATENEWDOJREQUESTHISTORYBYID: 'api/OnBoarding/GetCandidateNewDOJRequestHistorybyCandidateId/',
  GET_STATELISTBYCOUNTRYID: 'api/Location/GetStateListByCountryId?',
  GET_PAYGROUPDETAILSBYCONTRACTID: 'api/PayGroup/GetPayGroupDetails/',
  GET_ONBOARDINGCONFIGURATION: 'api/OnBoarding/GetOnboardingConfiguration/',
  // ** Onboarding service end 

  GET_MAPPEDCLIENTLISTBYUSER: 'api/Client/GetMappedClientListByUser',
  GET_MAPPEDCLIENTCONTRACTLISTBYUSER: 'api/Client/GetMappedClientContractListByUser?',
  GET_CLIENTLOCATIONBYCLIENTID: 'api/Client/GetClientLocationByClientId?',
  GET_COSTCODEBYTEAMID: 'api/Client/GetCostCodeByTeamd?',
  // ** WorkFlow  start

  POSTWORKFLOW: 'api/WorkFlow/CreateWorkFlowRequest',
  POSTWORKFLOWDOJREQ: 'api/WorkFlow/CreateNewDOJRequestWorkFlowRequest',
  UPDATE_PENDING_AT_USERID: 'api/WorkFlow/UpdatePendingAtUserIdModuleProcessTransaction',
  // ** WorkFlow end

  // ** Documents start here
  GET_DOCUMENTCATEGORY: 'api/DocumentCategory/DocumentCategory/FetchDocumentCategory',
  POST_OBJECTSTORAGE: 'api/ObjectStorage/StoreObject',
  DELETE_OBJECTSTORAGE: 'api/ObjectStorage/DeleteStoredObjectById?',
  GET_OBJECT_BY_ID: 'api/ObjectStorage/GetStoredObjectById',
  GET_DOC_BY_ID: 'api/GetObject/GetObject',
  GET_OBJECTSTORAGE: 'api/ObjectStorage/GetStoredObjectById?',
  GET_STOREDOBJECTSASZIPFILE: 'api/ObjectStorage/GetStoredObjectsAsZipFile',
  POST_GENERAL_MAIL: 'api/Employee/SendGeneralMail',
  POST_GENERALBULK_MAIL: 'api/Employee/BulkSendGeneralMail',
  POST_EMP_MISSING_DOC_MAIL: 'api/Employee/SendIndividualMail',
  GET_LOADCLIENTDOCUMENTLOOKUPDETAILS: 'api/Client/LoadClientDocumentsLookupDetails',
  POST_CLIENT_DOCUMENTS: 'api/Client/UpsertClientDocuments',
  GET_CLIENTDOCUMENTS_BY_CLIENTID: 'api/Client/GetClientDocumentsByClientId?',
  GET_CLIENTDOCUMENTS_BY_EMPLOYEEID: 'api/Client/GetClientDocumentsByEmployeeId?',
  GET_CLIENTDOCUMENTS_BY_ID: 'api/Client/GetClientDocumentsById?',
  DELETE_CLIENTDOCUMENTS: 'api/Client/DeleteClientDocuments',
  // **  document end here

  //*Client*/ Shashank 
  GET_LOOKUPCLIENTDETAILS: 'api/Client/LoadClientLookupDetails',
  POSTCLIENT: 'api/Client/InsertClientDetails',
  PUTCLIENT: 'api/Client/UpdateClientDetails',
  GETCLIENTCONTACTBYCLIENTID: 'api/Client/GetClientContactByClientId?',
  GET_LOOKUPTEAMDETAILS: 'api/Client/LoadTeamLookupDetails',
  GET_GETPAYPERIODBYPAYCYCLEID: 'api/Client/GetPayPeriodListByPayCyleId?',
  PUT_UPSERTTEAMDETAILS: 'api/Client/UpsertTeamDetails',
  GET_TEAMBYID: 'api/Client/GetTeamById?',
  GET_COSTCODELOOKUPDETAILSBYCLIENTID: 'api/Client/LoadCostCodeLookupDetailsbyClientId?',
  PUT_COSTCODEDETAILS: 'api/Client/UpsertCostCodeDetails',
  GET_COSTCODEDETAILSBYID: 'api/Client/GetCostCodeDetailsbyId?',
  //**Generic master */
  GETCOMPANY: 'api/Company/GetCompanyDetailsList',
  GETCLIENT: 'api/Client/GetClientDetailsList',
  GETCLIENTLIST: 'api/Client/GetClientList',
  GETClIENTBYID: 'api/Client/GetClientDetailsById?',
  GETCLIENTCONTRACT: 'api/Client/GetClientContract?',
  GETGENERICMASTER: 'api/GenericMaster/GetGenericMasterDetails',
  // GETCOMPANY: 'api/Company/GetCompanyDetailsList',
  // GETCLIENT: 'api/Client/GetClientDetailsList',
  // GETClIENTBYID: 'api/Client/GetClientDetailsById?',
  // GETCLIENTCONTRACT: 'api/Client/GetClientContract?',
  // GETGENERICMASTER: 'api/GenericMaster/GetGenericMasterDetails',
  POSTGENERICMASTER: 'api/GenericMaster/InsertGenericMasterDetails',
  PUTGENERICMASTER: 'api/GenericMaster/UpdateGenericMaster',
  DELETEGENERICMASTER: 'api/GenericMaster/DeleteGenericMaster',
  GET_USERMAPPEDCLIENTLOCATIONLIST: 'api/Client/GetUserMappedClientLocationList?',
  GET_USERMAPPEDCLIENTLIST: 'api/Client/GetUserMappedClientList?',
  //**ClientLocation */ 
  GETCITY: 'api/Location/GetCityListByStateId?',
  GETDISTRICT: 'api/Location/GetCityListByStateId?',
  GETCLIENTLOCATION: 'api/Client/GetClientLocationList',
  GETCLIENTLOCATIONBYCLIENTID: 'api/Client/GetClientLocationByClientId?',
  GETCLIENTLOCATIONName: 'api/Client/GetClientLocationByLocationName',
  POSTCLIENTLOCATION: 'api/Client/InsertClientLocationDetails',
  PUTCLIENTLOCATION: 'api/Client/UpdateClientLocationDetails',
  DELETECLIENTLOCATION: 'api/Client/DeleteClientLocationDetails',

  //**ClientContact */ 
  GETCLIENTCONTACT: 'api/Client/GetClientContactList',
  POSTCLIENTCONTACT: 'api/Client/InsertClientContactDetails',
  PUTCLIENTCONTACT: 'api/Client/UpdateClientContactDetails',
  DELETECLIENTCONTACT: 'api/Client/DeleteClientContactDetails',

  //**product Group */
  GETPRODUCTGROUP: 'api/Product/GetAllProductGroups',
  POSTPRODUCTGROUP: 'api/Product/UpsertProductGroup',
  PUTPRODUCTGROUP: 'api/Product/UpsertProductGroup',
  DELETEPRODUCTGROUP: 'api/Product/DeleteProductGroup',
  GETPRODUCTGROUPBYID: 'api/Product/GetProductGroupById/',
  //**product Type */
  GETPRODUCTTYPE: 'api/Product/GetAllProductTypes',
  POSTPRODUCTTYPE: 'api/Product/UpsertProductType',
  PUTPRODUCTTYPE: 'api/Product/UpsertProductType',
  DELETEPRODUCTTYPE: 'api/Product/DeleteProductType',
  GETPRODUCTTYPEBYID: 'api/Product/GetProductTypeById/',
  //**product */
  GETPRODUCT: 'api/Product/GetAllProduct',
  POSTPRODUCT: 'api/Product/UpsertProduct',
  PUTPRODUCT: 'api/Product/UpsertProduct',
  DELETEPRODUCT: 'api/Product/DeleteProduct',
  DELETEPRODUCTAPPLICABILITY: 'api/Product/DeleteProductApplicability',
  GETPRODUCTBYID: 'api/Product/GetProductById/',
  GETPRODUCTBYGroupID: 'api/Product/GetProductByGroupId/',
  GETALLTAXCODES: 'api/TaxCode/GetAllTaxCode',
  GETPAYGROUPDETAILSBYID: 'api/PayGroup/GetPayGroupDetailsbyId/',
  //**scale */

  POSTSCALE: 'api/Scale/UpsertScale',
  PUTSCALE: 'api/Scale/UpsertScale',
  GETSCALEBY_ID: 'api/Scale/GetScale?',
  DELETE_SCALE: 'api/Scale/DeleteScale',

  //paygroup

  GETPRODUCTWITHALLDATA: 'api/Product/GetAllProductwithData',
  GETALLPAYGROUPS: 'api/PayGroup/GetAllPayGroups',
  GETPAYGROUPPRODUCTBY_ID: 'api/PayGroup/GetPayGroupById/',
  PUTPAYGROUPPRODUCT: 'api/PayGroup/UpsertPayGroup',
  POSTPAYGROUPPRODUCT: 'api/PayGroup/UpsertPayGroup',
  DELETEPAYGROUPPRODUCT: 'api/PayGroup/DeletePayGroup',


  //**bank */
  GETBANK: 'api/Bank/FetchAllBankList',
  GETBANKBYSTATUS: 'api/Bank/FetchAllActiveBankByStatus',
  POSTBANK: 'api/Bank/InsertBankDetails',
  PUTBANK: 'api/Bank/UpdateBankDetails',
  DELETEBANK: 'api/Bank/DeleteBankDetails',
  GETBANKBYID: 'api/Bank/FetchBankDetailsById?',
  GETBANKBYCODE: 'api/Bank/FetchBankByCode',

  //**bankbranch */
  GETBANKBRANCHBYSTATUS: 'api/Bank/FetchAllActiveBankBranchList',
  GETBANKBRANCH: 'api/Bank/FetchAllBankBranchList',
  POSTBANKBRANCH: 'api/Bank/InsertBranchDetails',
  PUTBANKBRANCH: 'api/Bank/UpdateBranchDetails',
  DELETEBANKBRANCH: 'api/Bank/DeleteBankBranchDetails',
  GETBANKBRANCHBYID: 'api/Bank/FetchBranchDetailsById',
  GETBANKBRANCHBYFSCODE: 'api/Bank/FetchBranchByFinancialSystemCode',
  GETBANKBRANCHBYBANKID: 'api/Bank/FetchBankBranchByBankId',

  // ** Candiates Login
  VERIFICATION_LINK: 'api/OTP/GetValidInputTransactionData',
  CANDIDATE_LOGIN: 'api/OTP/LoginCandidate?',
  GET_UIOFFERDATA: 'api/OnBoarding/GetCanddateUIOfferData?',
  PUT_ACCEPTANCEREJECTION: 'api/OnBoarding/UpdateCandidateAccepatanceRejection?',
  PUT_RECORDSURVEYRESPONSES: 'api/OnBoarding/RecordSurveyResponses',
  // /* #region  employee transaction */
  PUT_INITIATE_EMPLOYEETRANSITION: 'api/OnBoarding/InitiateEmployeeTransition',
  Post_EMPLOYEE_MIGRATION: 'api/OnBoarding/UpdateCandidateOfferDetailsForMigration',
  GET_EMPLOYEELIST: 'api/Employee/GetEmployeeList/',
  GET_SELFSERVICELIST: 'api/Employee/GetSelfServiceList/',
  GET_INVESTMENTPROOFLIST: 'api/Employee/GetInvestmentProofList/',
  UPDATE_EMPLOYEEVOIDTRANSACTION: 'api/Employee/UpdateEmployeeVoidTransaction?',
  GET_EMPLOYEEDETAILSBYID: 'api/Employee/GetEmployeeDetailsById?',
  GET_EMPLOYEEDETAILSBYCODE: 'api/Employee/GetEmployeeDetailsByCode?',
  FETCH_EMPLOYEEDETAILSBYEMPLOYEECODE: 'api/Employee/FetchEmployeeDetailsByEmployeeCode?',
  POST_NEW_CALCULATESALARYBREAKUP: 'api/Employee/CalculateSalaryBreakUp',
  PUT_EMPLOYEELIFECYCLETRANSACTION: 'api/Employee/UpsertEmployeeLifeCycleTransaction',
  POST_EMPLOYEEPREVIEWLETTER: 'api/ELC/PreviewRevisionLetter',
  GET_MINIMUMWAGESDETAILS_EMPLOYEE: 'api/Employee/GetMinimumwagesDetails',
  POST_ELCWORKFLOW: 'api/WorkFlow/CreateELCWorkFlowRequest',
  POST_BULKELCWORKFLOW: 'api/WorkFlow/CreateBulkELCWorkFlowRequest',
  POST_FNFWORKFLOW: 'api/Workflow/CreateFnFWorkFlowRequest',
  PUTEMPLOYEEDETAILS: 'api/Employee/UpsertEmployeeDetails',
  PUT_MARKEMPLOYMENTCONTRACTFORSEPERATION: 'api/Employee/MarkEmploymentContractsForSeperation',
  POST_MARKEMPLOYEEFORSEPARATION: 'api/ELC/MarkEmployeeForSeperation',
  PUT_VOIDELCTRANSACTIONS: 'api/ELC/VoidELCTransactions',
  PUT_CANCELANYELCTRANSACTIONS: 'api/ELC/CancelAnyELCTransactions',
  POST_SAVECLIENTAPPROVALFOELC: 'api/ELC/SaveClientApprovalFoELC',
  POST_CONFIRMSEPARATION: 'api/ELC/ConfirmSeparation',
  GET_EMPLOYEEUILOOKUPDETAILS: 'api/Employee/LoadEmployeUILookupDetails/',
  GET_PREVIEWPAYSLIP: 'api/Payroll/PreviewPaySlip?',
  POST_UPDATEEMPLOYEETIMECARDCALCULATION: 'api/Payroll/UpdateEmployeeMarkedForCalculation?',
  DELETE_EMPLOYEEDETAILSBYEMPLOYEEID: 'api/Employee/DeleteEmployeeDetailsByEmployeeId?',
  POST_BANKDETAILSWORKFLOW: 'api/Workflow/CreateBankDetailsWorkFlowRequest',
  POST_INVESTMENTWORKFLOW: 'api/Workflow/CreateInvestmentWorkFlowRequest',
  GET_VALIDATEEMPLOYEEINVESTMENT: 'api/Employee/ValidateSubmitInvestment?',
  PUT_SENDLOGINCREDENTIALS: 'api/Employee/SendLoginCredentials',
  GET_IMPORTCONFIGURATIONTYPEID: 'api/GenericImport/GetImportConfigurationbyId?',
  POST_GENERICIMPORTBULK: 'api/GenericImport/GenericImport',
  GET_GETEMPLOYEEOFFICIALDOCUMENTS: 'api/Employee/GetEmployeeOfficialDocuments',
  getdumm: 'api/Employee/GetPaymentHistory?',
  POST_EMPLOYEEEXEMPTIONBILLDETAILS: 'api/Employee/UpsertEmployeeExemptionBillDetails',
  POST_EMPLOYEEJOURNEYDETAILS: 'api/Employee/UpsertEmployeeJourneyDetails',
  GET_EMPLOYEEEXEMPTIONBILLDETAILS: 'api/Employee/GetEmployeeExemptionBillDetails',
  POST_EMPLOYEEEXCEPTIONBILLLIST: '/api/Employee/UpsertEmployeeExemptionBillList',
  GET_ALLEMPLOYEEDEDUCTIONMANAGEMENTBYEMPLOYEEID: 'api/EmpDedn/GetAllEmployeeDeductionManagementbyEmployeeId?',
  GET_EMPLOYEEDEDUCTIONMANAGEMENTBYEMPID: 'api/EmpDedn/GetEmployeeDeductionManagementbyEmpId',
  GET_EMPLOYEEDEDUCTIONMANAGEMENTLOOKUPDETAILS: 'api/EmpDedn/LoadEmployeeDeductionManagementLookupDetails?',
  GET_EMPLOYEEDEDUCTIONDATA: 'api/EmpDedn/GetEmployeeDeductionData',
  PUT_EMPLOYEEDEDUCTIONMANAGEMENT: 'api/EmpDedn/UpsertEmployeeDeductionManagement',
  DELETE_EMPLOYEEDEDUCTIONMANAGEMENTBYID: 'api/EmpDedn/DeleteEmployeeDeductionManagementbyId?',
  PUT_EMPLOYEESCHEDULEDETAILS: 'api/EmpDedn/GenerateEmployeeScheduleDetails',
  GETEMPLOYEENEXTPAYPERIODID: 'api/EmpDedn/GetEmployeeNextPayPeriodId',
  GET_EMPLOYEETAXITEM: 'api/Employee/GetEmployeeTaxItem/',
  GET_EMPLOYEEACCORDIONDETAILS: 'api/Employee/GetEmployeeAccordionDetails/',
  GET_EMPLOYEELOOKUPDETAILSBYEMPID: 'api/Employee/EmployeeLookUpDetailsByEmployeeId/',
  GET_EMPLOYEEPAYMENTHISTORY: 'api/Employee/GetAnyPaymentHistory/',
  PUT_MARKEMPLOYMENTCONTRACTLWD: 'api/Employee/MarkEmploymentContractsLWD',
  GET_LOADEMPLOYEEINVESTMENTUILOOKUPDETAILS: 'api/Employee/LoadEmployeInvestmentUILookupDetails/',
  UPSERTEMPLOYEEINVESTMENTDETAILS: 'api/Employee/UpsertEmployeeInvestmentDetails',
  UPDATEEMPLOYEECONFIRMATIONDATE: 'api/Employee/UpdateEmployeeConfirmationDate',
  GET_NDCDOCUMENTLIST: 'api/Employee/GetEmployeeNDCDepartments?', // getting ndc doc list
  NOTIFY_NDCMAIL: 'api/Employee/NotifyNDCMail',
  POST_UPSERT_NDCDEPARTMENTDETAILS: 'api/Employee/UpsertNDCDepartmentDetails',
  GET_EMPLOYEE_NDC_TRANSACTION: 'api/Employee/GetNDCEmployeeTransaction?',
  POST_MARKANEMPLOYEEASBLACKLISTED: 'api/Employee/MarkAnEmployeeAsBlackListed',
  GET_EMPLOYEECONFIGURATION: 'api/Employee/GetEmployeeConfiguration/',
  POST_VALIDATEEMPLOYEEREQUESTAPPROVALBYHR : 'api/Employee/ValidateEmployeeRequestApprovalByHR',
  Get_EMPLOYEEINFORMATION:'api/Employee/GetEmployeesInfoForDirectory/',
  POST_REVOKESEPARATION : 'api/Employee/RevokeSeparation',
  GET_EMPLOYEEEXITTRANSACTIONHISTORY: 'api/Employee/GetEmployeeExitTransactionHistory/',
  //GENERATEEMPLOYEESCHEDULEDETAILS: 'api/EmpDedn/GenerateEmployeeScheduleDetails',
  /* #endregion */
  // NEW EMPLOYEE APIS
  GET_EMPLOYEEREQUIREDDETAILSBYID: 'api/Employee/GetEmployeeRequiredDetailsById/',
  GET_OPTIONALHOLIDAYBYANEMPLOYEEID: 'api/Attendance/GetOptionalHolidaysForAnEmployee/',
  // ONLINE JOINING KIT
  GET_EMPLOYEEADDRESSDETAILSFORJOININGKIT: 'api/Employee/GetEmployeeAddressDetailsForJoiningKit/',
  GET_JOININGKITFORAPPROVAL: 'api/Employee/GetJoiningKitsForApproval/',
  PUT_UPDATEONLINEJOININGKIT: 'api/Employee/UpdateOnlineJoiningKit',
  GET_ISEMPLOYEEALLOWEDTOEDITJOININGKIT: 'api/Employee/IsEmployeeAllowedToEditJoiningKit/',
  GET_JOININGKITDETAILS: 'api/Employee/GetJoiningKitDetails/',
  GET_EMPLOYEETABINFO:'api/Employee/GetEmployeeTabInfo/',
  GET_APPLICABLEEMPLOYEEDETAILS: 'api/Employee/GetApplicableEmployeeDetails/',
  GET_BIOMETRICDEVICES: 'api/Attendance/GetBiometricDevices/',
  POST_EXISTINGPUNCHDETAILS: 'api/Attendance/GetExistingPunchDetails',
  POST_PUSHBIOMETRICDATAMANUALLY: 'api/Attendance/PushBiometricDataManually',
  GET_RELATIONSHIPDETAILS: 'api/Attendance/GetRelationshipDetails',

  GET_ENTITLEMENTAVAILMENTREQUESTSFORAPPROVALBYHR: 'api/Attendance/GetEntitlementAvailmentRequestsForApprovalByHR',
  GET_ONDUTYREQUESTSFORAPPROVALBYHR: 'api/Attendance/GetOnDutyRequestsForApprovalByHR',
  POST_ValidateEntitlementAvailmentRequestByHR: 'api/Attendance/ValidateEntitlementAvailmentRequestByHR',
  POST_ValidateonDutyEntitlementAvailmentRequestByHR: 'api/Attendance/ValidateonDutyEntitlementAvailmentRequestByHR',
  PUT_ApproveRejectRegularizationDetailTypeByHR: 'api/Attendance/ApproveRejectRegularizationDetailTypeByHR?',

  //#region Onboarding related keys   

  RECRUITER_CANDIDATE_WORKFLOW_DETAILS: 'api/Candidate/RecruiterCandidateWorkFlowDetails',
  // http://34.67.27.23/hrsuite.api/api/Candidate/RecruiterCandidateWorkFlowDetails\1

  GET_DASHBOARD_DETAILS: 'api/Dashboard/GetDashboardDetails/',
  GET_ESS_DASHBOARD_DETAILS: 'api/Dashboard/GetESSDashboardDetails/',
  GET_ESS_DASHBOARD_DETAILSBYEMPLOYEEID: 'api/Dashboard/GetESSDashboardDetailsByEmployeeId/',

  // Page Layout
  GETPAGELAYOUT: 'api/PageLayout/FetchPageLayout?',
  POSTPAGELAYOUT: 'api/PageLayout/UpsertPageLayout',
  GETPAGELAYOUTDATASET: 'api/PageLayout/FetchDataset',
  GETCOlUMNORPARAMNAME: 'api/PageLayout/FetchColumnOrParamName',
  EXECUTEQUERY: 'api/PageLayout/ExecuteQuery',

  //Form Layout
  GETFORMLAYOUT: 'api/PageLayout/FetchFormLayout?',
  POSTFORMLAYOUT: 'api/PageLayout/UpsertFormLayout',
  UPSERTFORMDETAILS: 'api/PageLayout/UpsertFormDetails',
  UPLOADFORMDATATOCUSTOMSP: 'api/PageLayout/UploadFormDataToCustomSP',

  //Generic Import 
  GETIMPORTLAYOUT: 'api/PageLayout/FetchImportLayout?',
  POSTIMPORTLAYOUT: 'api/PageLayout/UpsertImportLayout',
  GETEXCELTEMPLATE: 'api/PageLayout/GetExcelTemplate',
  UPLOADEXCELDATA: 'api/PageLayout/UploadExcelData',
  //#endregion


  /* #region  PAYROLL */
  POST_PAYROLL_GENERATEPIS: 'api/Payroll/GeneratePIS',
  POST_PAYROLL_PROCESSTIMECARD: 'api/Payroll/ProcessTimeCards',
  POST_PAYROLL_PROCESSANYTIMECARD: 'api/Payroll/ProcessAnyTimeCards',
  POST_PAYROLL_VOIDTIMECARD: 'api/Payroll/VoidTimeCard',
  POST_PAYROLL_IMPORTPIS: 'api/payroll/ImportPIS',
  POST_PAYROLL_PVRSUBMISSION: 'api/Payroll/PVRSubmission',
  GET_ALLIMPORTEDPISLOGDATA: 'api/Payroll/GetAllImportedPISLogData?',
  GET_PAYROLLINPUTOUTPUTSHEETBYID: 'api/Payroll/GetPayrollInputOutputbyPVRId/',
  GET_DOWNLOADPAYSHEET: 'api/Payroll/GetPaysheetData',
  PUT_DOWNLOADPAYSHEET_TIMECARD: 'api/Payroll/GetPaysheetDatabyTimecardIds',
  PUT_INITIATESALEORDER: 'api/PayRun/InitiateSaleOrder',
  PUT_CONFIRMSALEORDER: 'api/PayRun/ConfirmSaleOrder',
  PUT_REMOVEPAYRUNDETAILS: 'api/PayRun/RemovePayrunDetails',
  DELETE_PAYRUN: 'api/PayRun/DeletePayRun?',
  GET_ADDITIONALTIMECARDDETAILS: 'api/PayRun/GetAdditionalTimeCardDetails?',
  GET_PAYTRANSACTIONDETAILSBYID: 'api/Payroll/GetPayTransctionDetails?',
  GET_PREVIEWSETTLEMENTBYPAYTRANSACTIONID: 'api/Payroll/PreviewSettlement?',
  GET_SALEORDERLOOKUPDETAILS: 'api/PayRun/LoadSaleOrderLookupDetails?',
  PUT_GETBILLINGSHEETDATABYSOID: 'api/Payroll/GetBillingSheetDatabySaleorderId',
  GET_EMPLOYEEPAYOUTDETAILS: 'api/PayOut/GetEmployeePayOutDetails?',
  GET_TERMINATIONTIMECARDDETAILS: 'api/Payroll/GetTerminationTimeCardDetailsByEmployeeId?',
  POST_VOIDSALARYTIMECARD: 'api/Payroll/VoidSalaryTimeCard',
  PUT_UPSERTPAYRUN: 'api/PayRun/UpsertPayRun',
  PUT_UPSERTPAYOUTINFORMATION: 'api/PayOut/UpsertPayoutInformation',
  REMOVE_PAYOUTINFORMATIONDETAILS: 'api/PayOut/RemovePayoutInformationDetails',
  DELETE_PAYOUT: 'api/PayOut/DeletePayoutInformation?',
  GET_PAYOUTLOOKUPDETAILS: 'api/PayOut/LoadPayOutLookupDetails?',
  PUT_GENERATEPAYOUTFILE: 'api/PayOut/GeneratePayOutFile',
  PUT_UPDATECOMPANYBANKINPAYOUTINFO: 'api/PayOut/UpdateCompanyBankInPayoutInfo',
  PUT_UPDATEPAYOUTINFORMATION: 'api/PayOut/UpdatePayoutInformation',
  GET_PAYOUTINFORMATIONBYID: 'api/PayOut/GetPayoutInformationbyId?',
  GET_SALEORDERSBYPAYRUNID: 'api/PayRun/GetSaleOrdersbyPayrunId?',
  PUT_UPDATESALEORDERSTATUSDETAILS: 'api/PayRun/UpdateSaleOrdersStatusDetails',
  POST_PROCESSINGBILLING: 'api/Payroll/ProcessBilling',
  PUT_SAVESALEORDER: 'api/PayRun/SaveSaleOrder',
  PUT_GETPAYROLLDETAILSFORQCSUBMISSION: 'api/Payroll/GetPayrollDetailsForQCSubmission',
  GET_VALIDATERECREATESO: 'api/PayRun/ValidateRecreateSO?',
  PUT_VOIDSALEORDERS: 'api/PayRun/VoidSaleOrders',
  PUT_MERGESALEORDER: 'api/PayRun/MergeSaleOrder',
  PUT_VALIDATETIMECARDTOREPROCESSBILLING: 'api/PayRun/ValidateEmployeeToReprocessBilling?',
  PUT_CALCULATETAX: 'api/Payroll/CalculateTax',

  GET_VALIDATEPAYOUTISLOCKED: 'api/PayOut/ValidatePayOutIsLocked?',
  // TIMECARD EDIT
  GET_TIMECARDDETAILSBYID: 'api/Payroll/GetTimeCardDetails/',
  GET_TIMECARDUILOOKUPDETAILS: 'api/Payroll/LoadTimeCardUILookupDetails?',
  PUT_SAVETIMECARDDETAILS: 'api/Payroll/SaveTimeCard',
  GET_GETLOPDETAILSFORREVOKE: 'api/Payroll/GetLopDetailsForRevokal?',
  GET_VALIDATETIMECARDTOPROCESS: 'api/Payroll/ValidateTimecardToProcess?',
  POST_PROCESSTIMECARD: 'api/Payroll/ProcessTimeCards',
  GET_PROCESSTIMECARDWOQ: 'api/Payroll/ProcessTimeCardWOQ?',

  //Reimbursement
  POST_UPSERTREIMBURSEMENTTIMECARDS: 'api/Reimbursement/UpsertTimeCards',

  //Report
  POST_BULKINSERTREPORTQUEUEMESSAGE: 'api/Report/BulkInsertReportQueueMessage',
  POST_PUSHREPORTMESSAGESTOQUEUE: 'api/Report/PushReportMessagesToQueue',

  //**CLient Contract */

  GET_CLIENTCONTRACTBYID: 'api/Client/GetClientContractById?',
  POSTCLIENTCONTRACTDETAILS: 'api/Client/InsertClientContractDetails',
  PUSTCLIENTCONTRACTDETAILS: 'api/Client/UpdateClientContractDetails',
  LOADCLIENTCONTRACTLOOKUPDETAILS: 'api/Client/LoadClientContractLookupDetails',
  GET_PAYPERIODLIST: 'api/Client/GetPayPeriodList',
  // GENERIC MASTER
  GET_GENERICMASTERBYMASTERTYPE: 'api/GenericMaster/GetGenericMasterListByMasterType?',
  GET_GENERICMASTERBYMASTERDATABYID: 'api/GenericMaster/GetGenericMasterById?',
  GET_MARKUPMAPPINGDETAILSBYCONTRACTID: 'api/ClientContract/GetMappingDetailsbyContractId?',
  GET_MARKUPMAPPINGLIST: 'api/ClientContract/GetMarkupMappingsList',
  PUT_UPSERCLIENTCONTRACTDETAILS: 'api/ClientContract/UpsertClientContract',
  GET_USERMAPPEDCLIENTCONTRACTLIST: 'api/ClientContract/GetUserMappedClientContractList?',

  // INVOICE
  GET_LOADPRODUCTLOOUPDETAILS: 'api/Product/LoadProductLookupDetails',
  PUT_UPSERTBILLINGPRODUCTGROUP: 'api/Billing/UpsertBillingProductGroup',
  GET_PRODUCTBILLINGGROUPCONTRACTID: 'api/Billing/GetProductBillingGroupByContractId?',
  GET_PRODUCTWISEINVOICEGROUP: 'api/Billing/GetProductWiseInvoiceGroupByContractId?',
  PUT_UPSERTPRODUCTWISEINVOICEGROUP: 'api/Billing/UpsertProductWiseInvoiceGroup',
  GET_ALLSALEORDERGROUPINGFIELD: 'api/Billing/GetAllClientSaleOrderGroupingField',
  PUT_UPSERTCLIENTSALEORDERGROUPING: 'api/Billing/UpsertClientSaleOrderGrouping',
  GET_CLIENTSALEORDERGROUPINGBYCONTRACTID: 'api/Billing/GetClientSaleOrderGroupingByContractId?',
  PUT_GENERATEINVOICE: 'api/Invoice/GenerateInvoice',
  PUT_SAVEINVOICE: 'api/Invoice/SaveInvoice',
  GET_GETINVOICEDETAILSBYID: 'api/Invoice/GetInvoiceDetailsbyId?',
  GET_PREVIEWINVOICE: 'api/Invoice/PreviewInvoice?',
  PUT_VOIDINVOICES: 'api/Invoice/VoidInvoices',
  PUT_PREVIEWSALEORDERINVOICE: 'api/Invoice/PreviewSaleOrderInvoice',
  PUT_CONTRACTROLLOVER: 'api/Payroll/ContractRollOver',
  GET_TAXCOMPUTATIONDETAILS: 'api/Payroll/GetTaxComputationDetails?',
  GET_TAXCOMPUTATIONDETAILSBYMONTHYEAR: 'api/Payroll/GetTaxComputationDetailsbyMonthYear?',
  GET_TAXCOMPUTATIONDETAILSBYFISCALYEAR: 'api/Payroll/GetTaxComputationDetailsbyFiscalYear?',
  GET_MONTHLYPAYROLLDATA: 'api/Payroll/GetMonthlyPayrollData?',
  GET_PFCHALLANREPORT: 'api/Payroll/GetPFChallanReport?',
  // FINANCE BANK API
  GET_YBFUNDBALANCE: 'api/PayOut/GetYBFundBalance?',
  PUT_INITIATEYBBANKPAYMENTTRANSACTION: 'api/PayOut/InitiateYBankPaymentTransaction',
  PUT_GETYBPAYMENTDETAILSSTATUS: 'api/PayOut/GetYBPaymentDetailsStatus',
  GET_PAYSLIPGENERATIONDATA: 'api/Report/GetDataForPayslipGeneration/',

  // ATTENDANCE AND LEAVE 
  UPDATE_INSERT_WORKSHIFTDEF: 'api/Attendance/UpdateWorkShiftDefinition',
  GETWORKSHIFTDEFFORCLIENT: 'api/Attendance/GetWorkShiftDefinitionsForAClient/',
  GET_GETEMPLOYEEENTITLEMENTLIST: 'api/Attendance/GetEmployeeEntitlementList/',
  GET_UPCOMINGLEAVEREQUEST: 'api/Attendance/GetUpcomingLeaveRequestByEmployeeId/',
  GET_ENTITLEMENTAVAILMENTREQUESTS: 'api/Attendance/GetEntitlementAvailmentRequests/',
  PUT_POSTENTITLEMENTAVAILMENTREQUEST: 'api/Attendance/PostEntitlementAvailmentRequest',
  GET_ENTITLEMENTAVAILMENTREQUESTSFORAPPROVAL: 'api/Attendance/GetEntitlementAvailmentRequestsForApproval',
  POST_VALIDATEENTITLEMENTAVAILMENTREQUEST: 'api/Attendance/ValidateEntitlementAvailmentRequest',
  POST_CANCELENTITLEMENTAVAILMENTREQUEST: 'api/Attendance/CancelEntitlementAvailmentRequest',
  PUT_UPSERTTIMECARDATTENDANCE: 'api/Attendance/UpsertTimecardAttendance',
  PUT_UPSERTENTITLEMENTDEFINITION: 'api/Attendance/UpsertEntitlementDefinition',
  POST_SUBMITPAYROLLINPUTSUBMISSIONBYTEAMID: 'api/Attendance/SubmitPayrollInputsSubmissionByTeamId',
  GET_PAYROLLINPUTSUBMISSIONUIDATA: 'api/Attendance/GetPayrollInputSubmissionUIData/',
  GET_PAYROLLINPUTSUBMISSIONUIDATABYTEAMID: 'api/Attendance/GetPayrollInputsSubmissionUIDatabyTeamId/',
  GET_PAYROLLINPUTSUBMISSIONUIDATABYTEAMIDMANAGERID: 'api/Attendance/GetPayrollInputsSubmissionUIDatabyTeamandManagerId/',
  GET_PAYROLLINPUTSUBMISSIONUIDATABYCLIENTID: 'api/Attendance/GetPayrollInputsSubmissionUIDatabyclientId/',
  GET_PAYROLLINPUTSUBMISSIONUIDATABYMANAGERID: 'api/Attendance/GetPayrollInputsSubmissionUIDatabyManagerId/',
  PUT_UPSERTTIMECARD: 'api/Attendance/UpsertTimeCard',
  PUT_SUBMITPAYROLLINPUTSUBMISSION: 'api/Attendance/SubmitPayrollInputsSubmission',
  GET_ENTITLEMENTAVAILMENTREQUESTSFORAPPROVALBYMANAGERID: 'api/Attendance/GetEntitlementAvailmentRequestsForApprovalbyManagerId/',
  GET_ATTENDANCECONFIGURATION: 'api/Attendance/GetAttendanceConfiguration/',
  GET_ATTENDANCEDATA: 'api/Attendance/GetAttendanceData/',
  GET_ATTENDANCEDATABYEMPID: 'api/Attendance/GetAttendanceDataByEmployeeId/',
  PUT_UPSERTEMPLOYEEATTENDANCEDETAILS: 'api/Attendance/UpsertEmployeeAttendanceDetails',
  PUT_UPSERTEMPLOYEEATTENDANCEBREAKUPDETAILS: 'api/Attendance/UpsertEmployeeAttendanceBreakUpDetails',
  PUT_PUNCHATTENDANCEDETAILS: 'api/Attendance/PunchAttendance',
  PUT_SUBMITEMPLOYEEATTENDANCEBREAKUPDETAILS: 'api/Attendance/SubmitEmployeeAttendanceBreakUpDetails',
  PUT_SUBMITREGULARIZEDATTENDANCE: 'api/Attendance/SubmitRegularizedAttendance',
  GETIPADDRESS: 'api/Attendance/GetIpAddress',
  GET_HOLIDAYCALENDARBASEDAPPLICABILITY: 'api/Attendance/GetHolidayCalendarBasedOnApplicability?',
  GET_REGULARIZATIONATTENDANCEDATA: 'api/Attendance/GetRegularizationAttendanceData/',
  GET_ATTENDACEPERIODBASEDEMPLOYEELIST: 'api/Attendance/GetAttendancePeriodBasedEmployeeList/',
  GET_ATTENDANCEBREAKUPDETAILSBYATTENDANCEPERIODID: 'api/Attendance/GetAttendanceBreakUpDetailsByAttendancePeriodId/',
  GET_ATTENDANCEDETAILSBYATTENDANCEPERIODID: 'api/Attendance/GetAttendanceDetails/',
  GET_VALIDATELEAVEREQUSTISVALIDTOUPDATE: 'api/Attendance/ValidateLeaveRequestIsValidToUpdate?',
  GET_ISTSERVERTIME: 'api/Attendance/GetISTServerTime',
  GET_WEEKOFFDAYS: 'api/Attendance/GetWeekOff/',
  GET_WEEKOFFDAYSBYEMPID: 'api/Attendance/GetWeekOffByEmployeeId/',
  GET_WORKSHIFTEMPLOYEEID: 'api/Attendance/GetWorkShiftEmployeeId/',
  POST_UPDATEENTITLEMENTREQUESTASPRESENT: 'api/Attendance/UpdateEntitlementAvailmentRequestAsPresent',
  PUT_SENDMAILFORREGULARIZEDEMPLOYEEATTENDNACE: 'api/Attendance/SendMailForRegularizeAttendanceEmployees',
  PUT_PUNCHATTENDANCE: 'api/Attendance/PunchAttendance',
  GET_REPORTINGMANAGER: 'api/Attendance/GetAllManagersForReportingManager/',
  GET_EMPLOYEEATTENDANCELISTUSINGEMPLOYEEID: 'api/Attendance/GetEmployeeAttendanceListUsingManagerId/',
  GET_ATTENDANCECONFIGURATIONBYEMPLOYEEID: 'api/Attendance/GetAttendanceConfigurationByEmployeeId/',
  GET_ATTENDANCEDETAILSBYFROMDATETODATE: 'api/Attendance/GetAttendanceDetails/',

  GET_ATTENDANCEGEOFENCINGCOORDINATEMAPPING: 'api/Attendance/GetAttendanceGeoFencingCoordinateMapping/',
  PUT_ATTENDACEGEOFENCECOORDINATESMAPPING: 'api/Attendance/UpsertAttendanceGeoFenceCoordinatesMapping',
  UPSERTATTENDANCECONFIGURATION: 'api/Attendance/UpsertAttendanceConfiguraionAndMapping',
  INSERTATTENDANCECONFIGURATION: 'api/Attendance/InsertAttendanceConfiguration',
  GET_ATTENDANCEMAPPING: 'api/Attendance/GetAttendanceConfigurationMapping/',
  GET_WORKSHIFTDEFINITION: 'api/Attendance/WorkShiftDefinition/',
  PUT_UPSERTWORKSHFITANDMAPPING: 'api/Attendance/UpsertWorkShiftAndMapping',
  PUT_UPDATEWORKSHIFTDEFINITION: 'api/Attendance/UpdateWorkShiftDefinition',
  GETCLIENTDETAILSBYCOMPANYID: 'api/Client/GetClientDetailsByCompanyId?',
  GETTEAMBYCONTRACTANDCLIENT: 'api/Client/GetTeamByContract?',
  GETEMPLOYEEBYTEAM: 'api/Employee/GetEmployeeByTeamId?',
  GET_DASHBOARDDETAILSBYROLECODEUSEID: 'api/Dashboard/GetDashboardDetailsByRoleCodeAndUserId/',
  GETEMPLOYEEYTDDETAILS: 'api/Payroll/GetEmployeeYTDDetails?',
  PUT_MARKASPRESENTBYEMPLOYEE: 'api/Attendance/MarkAttendanceAsPresentByEmployee',
  GET_CLIENTDASHBOARDDETAILS: 'api/Dashboard/getClientDashboardDetails/',
  PUT_UPSERTWEEKOFF: 'api/Attendance/UpsertWeekOff',
  GET_ATTENDANCEREPORT: 'api/Attendance/GetAttendanceReport/',
  GET_ATTENDANCEREPORTFORITC: 'api/Attendance/GetAttendanceReport_ITC/',
  GET_WEEKOFFLISTBYCLIENTID: 'api/Attendance/GetWeekOffForClient/',
  GET_TEAMSBYCLIENTID: '​/api​/Attendance​/GetTeamsForAClient​/',
  GET_ATTENDANCELEAVEREQUESTREPORT: 'api/Attendance/GetAttendanceLeaveRequestsReport/',
  GET_PUNCHINPUNCHOUTREPORT: 'api/Attendance/GetPunchInPunchOutReport/',
  GET_SEARCHFILTERFORSHIFTMAPPING: 'api/Attendance/GetAllSearchFilterDataForShiftMapping/',
  GET_WEEKOFFMAPPING: 'api/Attendance/GetWeekOffMapping/',
  PUT_APPROVEREJECTREGULARIZATION: 'api/Attendance/ApproveRejectRegularization',
  GET_ATTENDANCEREGULARIZEFORAMANAGER: 'api/Attendance/GetAttendanceRegularizationDetailsForAManager/',
  GET_ATTENDANCESUMMARYREPORT: 'api/Attendance/GetAttendanceSummaryReport/',
  GET_ATTENDANCESUMMARYREPORTDAILYBASIS: 'api/Attendance/GetAttendanceSummaryReportDailyBasis/',
  GET_ATTENDANCELEAVEREQUESTSREPORTFORITC: 'api/Attendance/GetAttendanceLeaveRequestsReport_ITC/',
  GET_PUNCHINPUNCHOUTREPORTFORITC: 'api/Attendance/GetPunchInPunchOutReport_ITC/',
  GET_CLIENTLOCATIONSFORANEMPLOYEE: 'api/Attendance/GetClientLocationsForAnEmployee/',
  PUT_REGULARISEATTENDANCE: 'api/Attendance/RegulariseAttendance?',
  PUT_APPROVEREJECTREGULARIZATIONDETAILTYPE: 'api/Attendance/ApproveRejectRegularizationDetailType?',
  GET_TEMPEMPLOYEEATTENDANCEBREAKUPDETAILSFORADATE: 'api/Attendance/GetTempEmployeeAttendanceBreakUpDetailsForADate/',
  GET_ISEMPLOYEEALLOWEDTOREGULARISEFORADATE: 'api/Attendance/IsEmployeeAllowedToRegulariseForADate/',
  GET_EMPLOYEEENTITLEMENTLOG: 'api/Attendance/GetEmployeeEntitlementLog/', 
  POST_EMPLOYEEENTITLEMENTBALANCE: 'api/Attendance/UpdateEmployeeEntitlementBalance',
  GET_EMPLOYEEENTITLEMENTREQUESTENDDATE: 'api/Attendance/GetEntitlementRequestEndDate/', 
  GET_EMPLOYEELEAVESTOMAP: 'api/Attendance/GetLeavesToMapToEmployee/', 
  POST_MAPENTITLEMENTTOEMPLOYEE: 'api/Attendance/MapEntitlementToEmployee',
  POST_MAPWEEKOFFFOREMPLOYEES: 'api/Attendance/MapWeekOffForEmployees',
  POST_MAPSHIFTFOREMPLOYEES: 'api/Attendance/MapShiftForEmployees',
  GET_AVAILABLEDATESFORCOMPOFFFORANEMPLOYEE: 'api/Attendance/FetchAvailableDatesForCompOffForAnEmployee?',
  GET_COMPENSATIONREPORT: 'api/Attendance/FetchCompensationReport?',
  PUT_NUMBEROFLEAVEDAYSAPPLIED: 'api/Attendance/GetNumberOfLeaveDaysApplied',
  GET_ONDUTYREQUESTS: 'api/Attendance/GetOnDutyRequests/',
  GET_EMPLOYEEODLIST: 'api/Attendance/GetEmployeeODList/',
  GET_ONDUTYREQUESTSFORAPPROVAL: 'api/Attendance/GetOnDutyRequestsForApproval',
  POST_CANCELONDUTYENTITLEMENTAVAILMENTREQUEST: 'api/Attendance/CancelOnDutyEntitlementAvailmentRequest',
  POST_ONDUTYREQUEST: 'api/Attendance/PostOnDutyRequest',
  POST_VALIDATEONDUTYREQUEST: 'api/Attendance/ValidateOnDutyEntitlementAvailmentRequest',
  PUT_NUMBEROFONDUTYDAYSAPPLIED: 'api/Attendance/GetNumberOfOnDutyDaysApplied',
  Get_AllEntitlementsByClientId: 'api/Attendance/GetAllEntitlementsByClientId/',
  POST_VALIDATEBULKLEAVETRANSACTION: 'api/Attendance/ValidateBulkLeaveTransaction',
  POST_INSERTBULKLEAVETRANSACTION:'api/Attendance/InsertBulkLeaveTransaction',
  POST_VALIDATEBULKPUSHBIOMETRICDATA: 'api/Attendance/ValidateBulkPushBiometricData',
  POST_INSERTBULKPUSHBIOMETRICDATA:'api/Attendance/InsertBulkPushBiometricData',
  POST_VALIDATEBULKODTRANSACTION: 'api/Attendance/ValidateBulkODTransaction',
  POST_INSERTBULKODTRANSACTION:'api/Attendance/InsertBulkODTransaction',
  GET_EMPLOYEEENTITLEMENTLISTFORPROXY:'api/Attendance/GetEmployeeEntitlementListForProxy/',
  POST_ENTITLEMENTAVAILMENTREQUESTFORPROXY:'api/Attendance/PostEntitlementAvailmentRequestForProxy',
  POST_ONDUTYREQUESTFORPROXY:'api/Attendance/PostOnDutyRequestForProxy',

  // ALERTS (NOTIFICATION)
  GET_PUSHNOTIFICATION: 'api/Alerts/GetNotifications',
  GET_PUSHNOTIFICATIONCOUNT: 'api/Alerts/GetUnReadNotificationCount',
  POST_UPDATENOTIFICATIONSTATUS: 'api/Alerts/UpdateNotificationStatus',
  POST_TESTNOTIFICATION: 'api/Alerts/TestInsertAlerts',
  POST_REGISTERTOKEN: 'api/Alerts/RegisterToken',

  GET_ISMANAGERALLOWEDTOREGULARIZE: 'api/Attendance/IsManagerAllowedToRegularize/',
  GET_SHIFTREQUESTBYEMPLOYEE: 'api/Attendance/GetShiftRequestsForAnEmployee/',
  GET_SHIFTREQUESTSBYMANAGER: 'api/Attendance/GetShiftRequestsForAManager/',
  PUT_SHIFTCHANGEREQUEST: 'api/Attendance/UpsertEmployeeShiftRequest',
  PUT_APPROVEREJECTSHIFTCHANGEREQUESTS: 'api/Attendance/ApproveRejectShiftChangeRequests/',
  GET_ISSHIFTCHANGEREQUESTEXISTS: 'api/Attendance/IsShiftChangeRequestExists/',
  GET_SENDATTENDANCEREMINDERMAILS: 'api/Attendance/SendAttendanceReminderMails?',
  GET_EMPLOYEESHIFTANDATTENDANCEDETAILSFORTODAY: 'api/Attendance/GetEmployeeShiftAndAttendanceDetailsForToday/',
  GET_SHIFTDETAILSFORANEMPLOYEE: 'api/Attendance/GetShiftDetailsForAnEmployee/',
  GET_SHIFTDETAILSFORMANAGER: 'api/Attendance/GetShiftDetailsForAManager/',


  //Permission
  POST_REQUESTPERMISSION: 'api/Attendance/RequestPermission',
  GET_RECENTRMISSIONS: 'api/Attendance/GetRecentPermissions/',
  GET_PERMISSIONSFOREMPLOYEEUI: 'api/Attendance/GetPermissionsForEmployeeUI/',
  GET_EMPLOYEEATTENDANCEBREAKUPDETAILSBYCURRENTDATE: 'api/Attendance/GetEmployeeBreakupDetailsByCurrentDate/',
  Post_Permission_Aprove_Reject: 'api/Attendance/DecidePermissionRequest',
  // EXPENSE MANAGEMENT
  GET_REIMBURSEMENTCONGIURATIONBYEMPLOYEEID: 'api/Reimbursement/GetReimbursementConfigurationByEmployeeId/',
  GET_ExpenseEligibilityCriteriaByEmployeeId: 'api/Reimbursement/GetExpenseEligibilityCriteriaByEmployeeId/',
  PUT_UPSERTEXPENSECLAIMREQUEST: 'api/Reimbursement/UpsertExpenseClaimRequest',
  PUT_UPSERTEXPENSEBATCH: 'api/Reimbursement/UpsertExpenseBatch',
  PUT_SUBMITEXPENSECLAIMREQUEST: 'api/Reimbursement/SubmitExpenseClaimRequest',
  PUT_SUBMITEXPENSEBATCH: 'api/Reimbursement/SubmitExpenseBatch',
  PUT_VALIDATEEXPENSEAMOUNT: 'api/Reimbursement/ValidateExpenseAmount',
  PUT_MIGRATEEXPENSE: 'api/Reimbursement/MigrateExpense',
  PUT_CREATEEXPENSEPAYOUTBATCH: 'api/PayOut/CreateExpensePayoutBatch',

  // PENNY DROP PAYMENT
  PUT_INITITATEPENNYDROPPAYMENTTRANSACTION: 'api/PayOut/InitiatePennyDropPaymentTransaction',
  PUT_GETYBPENNYDROPSTATUS: 'api/PayOut/GetYBPennyDropStatus',

  GETCLIENTLOCATIONBYCLIENTID1: 'api/Employee/GetEmployeeRequiredDetailsById/',
  //Notification
  POST_PUSHNOTIFICATIONMESSAGESTOQUEUE: 'api/Notification/PushNotificationMessagesToQueue',
  // testing dummy
  post_billentry: 'api/Employee/UpsertEmployeeExemptionBillDetails',
  get_billentry: 'api/Employee/GetEmployeeExemptionBillDetails/',


  /* #endregion */

  /*manager screen employee request permission tab*/
  get_Manager_PermissionsForApproverUI: 'api/Attendance/GetPermissionsForApproverUI',
  get_Manager_PermissionsForWOW: 'api/Attendance/GetWOWRequestForApproverUI',
  GETRECENTWOWREQUESTSMETHOD: 'api/Attendance/GetRecentWOWRequests/',
  Post_WOW_Aprove_Reject: 'api/Attendance/SubmitWOWRequest',
  /*Compensation Claims*/
  GetCompensationDetailsForEmployeeUI: 'api/Attendance/GetCompensationDetailsForEmployeeUI/',
  /*Attendance pge Claim Type Submit*/
  Post_ClaimType: 'api/Attendance/RequestWOW',
  /*Avail Compoff CompensationClaims*/
  Post_Avail_Individual_Compensation: 'api/Attendance/AvailIndividualCompensation',
  Post_Avail_Multy_Compensation: 'api/Attendance/AvailCompensation',
  Get_Emp_WOW_Req: 'api/Attendance/GetWOWRequestsForEmployeeUI/',

  postEmpRequestWFH: 'api/Attendance/RequestWFH',
  postManagerSubmitWfhRequest: 'api/Attendance/SubmitWFHRequest',
  GetManagerWfhGrid: 'api/Attendance/GetWFHRequestForApproverUI',

  postEmpRequestOD: 'api/Attendance/RequestOD',
  postManagerSubmitOdRequest: 'api/Attendance/SubmitODRequest',
  GetManagerOdGrid: 'api/Attendance/GetODRequestForApproverUI',

  GetInitManagerCards: 'api/Attendance/GetApplicableEmployeeRequestsForApproverUI',
  GetInitEmployeeCards: 'api/Attendance/GetApplicableEmployeeRequestsForEmployeeUI',
  GetODRequestsForEmployeeUISrvc: 'api/Attendance/GetODRequestsForEmployeeUI/',
  GetWFHRequestsForEmployeeUISrvc: 'api/Attendance/GetWFHRequestsForEmployeeUI/',
  //salary details
  GetEmployeeActiveRatesets: 'api/Employee/GetEmployeeActiveRatesets/',

  // testing purpose only 
  GetRequiredCompanySettingsList: 'api/CompanySettings/GetRequiredCompanySettingsList?',

  PUT_CREATELOGINUSERDETAILS: 'api/OnBoarding/CreateLoginUserDetails',
  GET_LOGINUSERDETAILS: 'api/OnBoarding/GetLoginUserDetails/',
  //Investment Submission Slot
  GET_INVESTMENTSUBMISSIONSLOTS: 'api/Client/GetInvestmentSubmissionSlots/',
  GET_INVESTMENTSUBMISSIONSLOTSBYID: 'api/Client/GetInvestmentSubmissionSlotById?',
  PUT_UPSERTINVESTMENTSUBMISSIONSLOT: 'api/Client/UpsertInvestmentSubmissionSlot',
  PUT_INACTIVEINVESTMENTSUBMISSIONSLOT: 'api/Client/InActivateInvestmentSubmissionSlot',
  DELETE_INVESTMENTSUBMISSIONSLOT: 'api/Client/DeleteInvestmentSubmissionSlot?',
  GET_LOADINVESTMENTSUBMISSIONSLOT: 'api/Client/LoadInvestmentSubmissionSLot',
  // FBP 
  GET_LOADFBPSUBMISSIONSLOT: 'api/Client/LoadFBPSubmissionSLot',
  GET_FBPSUBMISSIONSLOTSBYID: 'api/Client/GetFBPSubmissionSlotById?',
  PUT_UPSERTFBPSUBMISSIONSLOT: 'api/Client/UpsertFBPSubmissionSlot',
  DELETE_FBPSUBMISSIONSLOT: 'api/Client/DeleteFBPSubmissionSlot?',
  PUT_INACTIVEFBPSUBMISSIONSLOT: 'api/Client/InActivateFBPSubmissionSlot',
  GET_FBPCOMPONENTSFOREMPLOYEE: 'api/Employee/GetFBPComponentsForAnEmployee/',
  GET_ISFBPAPPLICABLEFOREMPLOYEE: 'api/Employee/IsFBPApplicableForAnEmployee/',
  GET_ISFBPSLOTENABLEDFOREMPLOYEE: 'api/Employee/IsFBPSlotEnabled/',
  GET_ALLFBPSLOTSFORANEMPLOYEE: 'api/Employee/GetAllFBPSubmissionsForAnEmployee/',
  GET_FBPCONFIGFOREMPLOYEE: 'api/Employee/GetFBPConfigurationForAnEmployee/',
  PUT_FBPEMPLOYEELIFECYCLETRANSACTION: 'api/Employee/UpsertEmployeeLifeCycleTransactionForFBP/',
  GETALLBRANCHDETAILS: 'api/Client/GetAllBranchDetails/',
  GETBRANCHGAPREPORT: 'api/Client/GetBranchGapReport?',
  GET_LOADPAYOUTLOOKUPDETAILSFORITC: 'api/Client/LoadPayOutLookupDetailsForITC?',
  GET_BLACKLISTREASONS: 'api/Employee/FetchBlackListingReasons?',

  // DYNAMIC APIS 
  GET_EMPLOYEEMASTERINFORFORRESIGNATION: 'api/Employee/GetMasterInfoForResignation/',
  POST_VALIDATERESIGNATION: 'api/Employee/ValidateResignation',
  POST_VALIDATERESIGNATIONBYHR: 'api/Employee/ValidateResignationByHR',
  POST_EMPLOYEERESIGNATIONDETAILS: 'api/Employee/UpsertEmployeeResignationDetails',
  POST_REVOKEEMPLOYEERESIGNATIONREQUEST: 'api/Employee/RevokeResignationRequest',
  GET_ATTENDANCEREGULARIZATIONREQUESTDETAILS: 'api/Attendance/GetAttendanceRegularizationRequestDetails/',
  POST_VALIDATEREGULARIZATION: 'api/Attendance/ValidateRegularization',
  GET_GETENTITLEMENTAVAILMENTREQUESTBYID: 'api/Attendance/GetEntitlementAvailmentRequestById/',
  POST_VALIDATEREGULARIZATION_DETAILTYPE: 'api/Attendance/ValidateRegularizationDetailType',
  GET_ATTENDANCEREGULARIZATIONREQUESTDETAILS_DETAILTYPE: 'api/Attendance/GetAttendanceRegularizationRequestDetails_DetailType/',

  PUT_UPSERTJOB: 'api/RLCTransaction/UpsertRLCApplicantDocuments',
  PUT_CREATEEMPLOYEEATTNBREAKUPDETAILS: 'api/Attendance/CreateEmployeeAttendanceBreakUpDetails/',
  PUT_CREATEEMPLOYEEATTNBREAKUPDETAILSFORNEXTPERIOD: 'api/Attendance/CreateEmployeeAttendanceBreakUpDetailsForNextPeriod/',
  GENERATEPDFDOCUMENT: 'api/Employee/DownloadTaxslip',
  GENERATEHTMLTOPDFDOCUMENT: 'api/Employee/DownLoadHTMLtoPDF',

  // Notification
  POST_NOTIFICATIONMESSAGE: 'api/Notification/PushNotificationMessagesToQueue',

  // Timesheet
  PUT_UPSERTTIMESHEETHEADER: 'api/Timesheet/UpsertTimesheetHeader',
  GET_TIMESHEETSFORANEMPLOYEE: 'api/Timesheet/GetTimesheetsForAnEmployee/',
  GET_TIMESHEETINFORMATION: 'api/Timesheet/GetTimesheetInformation/',
  GET_PENDINGTIMESHEETSFORAMANAGER: 'api/Timesheet/GetPendingTimesheetsForAManager/',
  PUT_APPROVEREJECTTIMESHEETS: 'api/Timesheet/ApproveRejectTimesheets/',
  GET_PROJECTSFORANEMPLOYEE: 'api/Timesheet/GetProjectsForAnEmployee/',
  GET_ACTIVITIESFORAPROJECT: 'api/Timesheet/GetActivitiesForAProject/',
  GET_SAVEDTIMESHEETSFORANEMPLOYEE: 'api/Timesheet/GetSavedTimesheetsForAnEmployee/',
  GET_TIMESHEETCONFIGURATIONFORANEMPLOYEE: 'api/Timesheet/GetTimesheetConfigurationForAnEmployee/',
  GET_PENDINGTIMESHEETSFORANEMPLOYEE: 'api/Timesheet/GetPendingTimesheetsForAnEmployee/',
  GET_DATAFORPROJECTHOURSCHART: 'api/Timesheet/GetDataForProjectHoursChart/',
  GET_APPROVEDREJECTEDTIMESHEETSFORAMANAGER: 'api/Timesheet/GetApprovedRejectedTimesheetsForAManager/',
  GET_EMPLOYEEWISETIMESHEETREPORT: 'api/Timesheet/GetEmployeeWiseTimesheetReport/',
  GET_PROJECTWISETIMESHEETREPORT: 'api/Timesheet/GetProjectWiseTimesheetReport/',
  GET_TIMESHEETREPORT: 'api/Timesheet/GetTimesheetReport/',
  PUT_UPSERTPROJECT: 'api/Timesheet/UpsertProject',
  PUT_UPSERTEMPLOYEEPROJECTMAPPING: 'api/Timesheet/UpsertEmployeeProjectMapping',
  PUT_UPSERTPROJECTACTIVITYMAPPING: 'api/Timesheet/UpsertProjectActivityMapping',
  GET_PROJECTSFORACLIENT: 'api/Timesheet/GetProjectsForAClient/',
  GET_EMPLOYEEPROJECTMAPPING: 'api/Timesheet/GetEmployeeProjectMapping/',

  // AADHAAR INTEGRATION API

  PUT_SENDAADHAAROTP: 'api/Integration/SendAadhaarOTP',
  PUT_VERIFYAADHAAR: 'api/Integration/VerifyAadhaar',
  PUT_VERIFYUNIQUENUMBER : 'api/Integration/VerifyUniqueNumber',

  // REPORTS API
  GET_MASTERANDREPORTEEDATAFORCORRECTION: 'api/Adhoc/GetMasterAndReporteeDataForCorrection/',
  POST_INSERTEMPLOYEEDATACORRECTIONLOG: 'api/Adhoc/InsertEmployeeDataCorrectionLog',
  GET_PENDINGEMPDATACORRECTIONS : 'api/Adhoc/GetPendingEmpDataCorrections/',
  POST_UPDATEEMPLOYEEATTRIBUTES : 'api/Adhoc/UpdateEmployeeAttributes',
  GET_APPLICABLECITIESBYUSERID : 'api/Adhoc/GetApplicableCitiesByUserId/',

    // GetGroupByClientId

    GET_GROUP_BY_CLIENTID: 'api/Client/GetGroupByClientId?',
  
  //Family Details
  GET_VALIDATEEMPPLOYEEANDGETDETAILSBYID: 'api/Employee/ValidateEmployeeAndGetDetailsById/',
};


